# Sample .travis.yml for R projects

language: r
cache: packages
warnings_are_errors: false
sudo: required

notifications:
  email:
    on_success: change
    on_failure: change

before_install:
  - sudo apt-get update -q
  - sudo apt-get install gcc-4.8 -y

apt_packages:
  - libgsl0-dev

use_bioc: true
bioc_required: true

# Install packages from github
r_github_packages:
  - thierrygosselin/stackr
  - zhengxwen/SNPRelate
  - hadley/multidplyr

