# Sample .travis.yml for R projects

language: r
cache: packages
warnings_are_errors: false
sudo: required
dist: trusty


notifications:
  email:
    on_success: change
    on_failure: change

use_bioc: true
bioc_required: true
